[build]
  command = "npm run build"
  publish = "dist"
[[redirects]]
	from = "/*"
	to =  "/login"
	status = 200
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # ensures native fetch support
